webtalk_init -webtalk_dir C:/Users/andre/Projects/IEE2463-SEP-Proyecto-2-Z8/project_1/tmp_edit_project.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon May 19 09:51:58 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "labtool" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d011e6fb-0da9-4b2b-aa54-565e41ee2e95" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "fe487c8c-b094-4386-8efa-f58255618de0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "13th Gen Intel(R) Core(TM) i5-1335U" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key chain -value "0000400013722093" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "0000400013722093" -context "labtool\\usage"
webtalk_add_data -client labtool -key pgmcnt -value "00:00:00" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Digilent/Zybo Z7/15000000:" -context "labtool\\usage"
webtalk_transmit -clientid 2393317841 -regid "" -xml C:/Users/andre/Projects/IEE2463-SEP-Proyecto-2-Z8/project_1/tmp_edit_project.hw/webtalk/usage_statistics_ext_labtool.xml -html C:/Users/andre/Projects/IEE2463-SEP-Proyecto-2-Z8/project_1/tmp_edit_project.hw/webtalk/usage_statistics_ext_labtool.html -wdm C:/Users/andre/Projects/IEE2463-SEP-Proyecto-2-Z8/project_1/tmp_edit_project.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
