# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/proyectosep2/IEE2463-SEP-Proyecto-2-Z8/full_hardware/vivado/vivado.srcs/sources_1/bd/DEMO/ip/DEMO_processing_system7_0_0/DEMO_processing_system7_0_0.xci
# IP: The module: 'DEMO_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/proyectosep2/IEE2463-SEP-Proyecto-2-Z8/full_hardware/vivado/vivado.srcs/sources_1/bd/DEMO/ip/DEMO_processing_system7_0_0/DEMO_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DEMO_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/proyectosep2/IEE2463-SEP-Proyecto-2-Z8/full_hardware/vivado/vivado.srcs/sources_1/bd/DEMO/ip/DEMO_processing_system7_0_0/DEMO_processing_system7_0_0.xci
# IP: The module: 'DEMO_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/proyectosep2/IEE2463-SEP-Proyecto-2-Z8/full_hardware/vivado/vivado.srcs/sources_1/bd/DEMO/ip/DEMO_processing_system7_0_0/DEMO_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DEMO_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
