# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/U/2025/Primer_semestre/SEP/LAB10/project_1/project_1.srcs/sources_1/bd/DEMO/ip/DEMO_axi_gpio_1_0/DEMO_axi_gpio_1_0.xci
# IP: The module: 'DEMO_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/U/2025/Primer_semestre/SEP/LAB10/project_1/project_1.srcs/sources_1/bd/DEMO/ip/DEMO_axi_gpio_1_0/DEMO_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DEMO_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/U/2025/Primer_semestre/SEP/LAB10/project_1/project_1.srcs/sources_1/bd/DEMO/ip/DEMO_axi_gpio_1_0/DEMO_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DEMO_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/U/2025/Primer_semestre/SEP/LAB10/project_1/project_1.srcs/sources_1/bd/DEMO/ip/DEMO_axi_gpio_1_0/DEMO_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DEMO_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/U/2025/Primer_semestre/SEP/LAB10/project_1/project_1.srcs/sources_1/bd/DEMO/ip/DEMO_axi_gpio_1_0/DEMO_axi_gpio_1_0.xci
# IP: The module: 'DEMO_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/U/2025/Primer_semestre/SEP/LAB10/project_1/project_1.srcs/sources_1/bd/DEMO/ip/DEMO_axi_gpio_1_0/DEMO_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DEMO_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/U/2025/Primer_semestre/SEP/LAB10/project_1/project_1.srcs/sources_1/bd/DEMO/ip/DEMO_axi_gpio_1_0/DEMO_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DEMO_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/U/2025/Primer_semestre/SEP/LAB10/project_1/project_1.srcs/sources_1/bd/DEMO/ip/DEMO_axi_gpio_1_0/DEMO_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DEMO_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
